// Generated by: gen
// TypeWriter: gen
// Directive: +gen on *shirolet.Hold

// See http://clipperhouse.github.io/gen for documentation

package shirolet

// Holds is a slice of type *Hold. Use it where you would use []*Hold.
type Holds []*Hold

// Any verifies that one or more elements of Holds return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv Holds) Any(fn func(*Hold) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// All verifies that all elements of Holds return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv Holds) All(fn func(*Hold) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}
