// Generated by: gen
// TypeWriter: gen
// Directive: +gen on shirolet.group

// See http://clipperhouse.github.io/gen for documentation

package shirolet

// groups is a slice of type group. Use it where you would use []group.
type groups []group

// Any verifies that one or more elements of groups return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv groups) Any(fn func(group) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// All verifies that all elements of groups return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv groups) All(fn func(group) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}
