// Generated by: gen
// TypeWriter: gen
// Directive: +gen on shirolet.Pgroup

// See http://clipperhouse.github.io/gen for documentation

package shirolet

// Pgroups is a slice of type Pgroup. Use it where you would use []Pgroup.
type Pgroups []Pgroup

// Any verifies that one or more elements of Pgroups return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv Pgroups) Any(fn func(Pgroup) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// All verifies that all elements of Pgroups return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv Pgroups) All(fn func(Pgroup) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}
